EGI-Federation/cloud-info-provider

rpm/cloud-info-provider.spec

Hi all,
to create an up-to-date RPM, I changed the names to be consistent with the new repository as well as two bogus dates (which are now checked by rpmbuild).
Greetings
Andre

Small RPM spec changes

---

cloud_bdii/core.py
cloud_bdii/exceptions.py
cloud_bdii/providers/opennebula.py
cloud_bdii/providers/static.py
cloud_bdii/tests/test_core.py
cloud_bdii/tests/test_opennebula.py
cloud_bdii/tests/test_openstack.py
cloud_bdii/tests/test_static.py
cloud_bdii/tests/utils.py
cloud_bdii/utils.py
requirements.txt
test-requirements.txt
tox.ini

Add Py34 support

---

cloud_info/providers/opennebula.py
cloud_info/providers/openstack.py
cloud_info/tests/data.py
cloud_info/tests/test_openstack.py
etc/templates/compute_bdii.ldif

@arax please check that it looks good for ONE
@alvarolopez tested against IFCA seems to work fine, but code may need changes to adapt to newer versions of the python-novaclient

Add disk size as OtherInfo of Resource templates

---

rpm/cloud-info-provider.spec

Fix dates in changelog to prevent PBR from exiting.

It is not possible to trick PBR about the versions dates

---

README.md

Always clean previous build attempts before building a deb.

README: always clean before building a deb.

---

README.md
cloud_info/providers/opennebula.py
debian/control
requirements.txt
rpm/cloud-info-provider.spec
tox.ini

tox.ini: fix bandit call

---

rpm/cloud-info-provider.spec

fix typo in python-defusedxml dependency

RPMSPEC: fix typo in python-defusedxml dependency.

---

debian/changelog
rpm/cloud-info-provider.spec

Update changelogs and versions.

Prepare version 0.8.2

---

README.md
debian/changelog
debian/control
requirements.txt
rpm/cloud-info-provider.spec
test-requirements.txt

defusedxml is only required for ON.

defusedxml is only required when using the OpenNebula provider

---

README.md

Copy spec and source from inside the docker to fix ownership in the container.

README: update RPM build instructions to fix issue with files/directories.

---

cloud_info/core.py
cloud_info/importutils.py
cloud_info/providers/opennebula.py
cloud_info/providers/openstack.py
cloud_info/tests/base.py
cloud_info/tests/data.py
cloud_info/tests/test_base_provider.py
cloud_info/tests/test_core.py
cloud_info/tests/test_importutils.py
cloud_info/tests/test_opennebula.py
cloud_info/tests/test_openstack.py
cloud_info/tests/test_static.py
requirements.txt
test-requirements.txt

OpenStack authentication using Keystone API v3. API v2.0 is no more available, only API v3 is supported.

OpenStack authentication using Keystone API v3

---

README.md

As repository was transfered from @EGI-FCTF, update references in the README.

Update organization name.

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
LICENSE.txt

Some files have been added to this repo, in the .github hidden directory
in order to improve the community health and help pass the corresponding
[inspec profile](https://github.com/brucellino/black-panther).
Added files include:
- code of conduct, with emphasis on how we deal with issues.
Adapted from the contributor covenant
- contributing guidelines
- issue and pull request templates
this addresses #76

Add files to improve community health

---

cloud_info/providers/opennebula.py

Add unicode (utf8) support
----
**Related issue :** https://ggus.eu/index.php?mode=ticket_info&ticket_id=135595

Add unicode (utf8) support

---

AUTHORS
COPYRIGHT
LICENSE.txt
setup.cfg

Change ownership and copyrights: ownership is explicitly retained by the authors.
Fix #76.

Update copyright information, ownership is retained by authors

---

.gitignore
.travis.yml
README.md
debian/control
debian/copyright
debs/cloud-info-provider-opennebula/debian/control
debs/cloud-info-provider-opennebula/debian/copyright
debs/cloud-info-provider-openstack/debian/control
debs/cloud-info-provider-openstack/debian/copyright

Work in progress, not finalized yet.
* Automatically lint markdown and RPMs. Fix errors.
* Test each python version in a dedicated environment.
* Build packages in Docker containers.

Test and build with travis

---

AUTHORS
debian/changelog
debs/cloud-info-provider-opennebula/debian/changelog
debs/cloud-info-provider-openstack/debian/changelog
rpm/cloud-info-provider-opennebula.spec
rpm/cloud-info-provider-openstack.spec
rpm/cloud-info-provider.spec

Bump build descriptors and update AUTHORS.

Prepare release 0.10.0

---

.travis.yml
debian/changelog
debs/cloud-info-provider-opennebula/debian/changelog
debs/cloud-info-provider-openstack/debian/changelog
rpm/cloud-info-provider-opennebula.spec
rpm/cloud-info-provider-openstack.spec
rpm/cloud-info-provider.spec

Travis: fix path to RPM packages

---

etc/templates/compute.glue21

This is a set of commits to have the rendering ready for GlueSchema2.1 (draft)
----
**Related issue :** #88

Glue2.1 verification

---

etc/templates/compute.glue21

Adapt (fix) compute.glue21 template to the auth:project_id schema agreed in 6be4acf9b80a04ea80259a9958787b6856c5e8be

Remove non-ascii characters

---

cloud_info_provider/providers/opennebula.py
cloud_info_provider/providers/openstack.py
cloud_info_provider/providers/static.py
cloud_info_provider/tests/test_opennebula.py
cloud_info_provider/tests/test_openstack.py
cloud_info_provider/tests/test_static.py
etc/sample.openstack.yaml
etc/templates/compute.glue21

Remove as much as possible any default values from config so user only needs to configure what's really specific to the site.
----

Do not require default values in config

---

cloud_info_provider/providers/opennebula.py
cloud_info_provider/providers/openstack.py
cloud_info_provider/tests/test_opennebula.py
cloud_info_provider/tests/test_openstack.py
etc/templates/compute.glue21

Gets the project information of shares at the specific providers
----

Fix projects

---

tox.ini

Add a new test to ensure non-ascii characters are not introduced in the templates.
----
**Related issue :** #131

Test non-ascii chars presence in templates

---

cloud_info_provider/providers/openstack.py

Fixes template copying which before caused all images to contain the same information.

Fix basempuri

---

cloud_info_provider/providers/gocdb.py
cloud_info_provider/providers/ooi.py
cloud_info_provider/providers/opennebula.py
cloud_info_provider/providers/openstack.py
cloud_info_provider/tests/test_gocdb.py
cloud_info_provider/tests/test_openstack.py
etc/templates/compute.glue21

add information about the endpoint as found in GOC_DB
----
**Related issue :** #120

Add GOCDB information

---

cloud_info_provider/core.py
cloud_info_provider/exceptions.py
cloud_info_provider/providers/__init__.py
cloud_info_provider/providers/gocdb.py
cloud_info_provider/providers/openstack.py
cloud_info_provider/providers/ssl_utils.py
cloud_info_provider/tests/test_base_provider.py
cloud_info_provider/tests/test_opennebula.py
cloud_info_provider/tests/test_static.py

Adds a new global debug option that can be used to increase the level of debug of the tool. 
----
**Related issue :** #81

Add debug option

---

cloud_info_provider/providers/opennebula.py
cloud_info_provider/providers/openstack.py
cloud_info_provider/providers/static.py
etc/sample.opennebula.yaml
etc/sample.opennebularocci.yaml
etc/sample.openstack.yaml
etc/sample.static.yaml
etc/templates/compute.glue21

Validating GLUE 2.1 output with latest GLUE 2.1 draft.
Enabling some network-related information.
WIP, not ready for merge yet

Validate glue21

---

README.md
RELEASING.md

Document release management

---

.zenodo.json
RELEASING.md
debian/changelog
debian/control
debs/cloud-info-provider-opennebula/debian/changelog
debs/cloud-info-provider-openstack/debian/changelog
rpm/cloud-info-provider-opennebula.spec
rpm/cloud-info-provider-openstack.spec
rpm/cloud-info-provider.spec

Prepare release 0.11.0

---

.zenodo.json
RELEASING.md
debian/changelog
debs/cloud-info-provider-opennebula/debian/changelog
debs/cloud-info-provider-openstack/debian/changelog
rpm/cloud-info-provider-opennebula.spec
rpm/cloud-info-provider-openstack.spec
rpm/cloud-info-provider.spec

Bump to 0.11.1

---

debs/cloud-info-provider-openstack/debian/changelog

Fix build of OpenStack deb package.

Fix build of OpenStack deb package

---

RELEASING.md

Document appdb update as part of the release management.

Document appdb update

---

.zenodo.json
debian/changelog
debs/cloud-info-provider-opennebula/debian/changelog
debs/cloud-info-provider-openstack/debian/changelog
rpm/cloud-info-provider-opennebula.spec
rpm/cloud-info-provider-openstack.spec
rpm/cloud-info-provider.spec

Prepare release 0.11.2

---

RELEASING.md

Document pushing packages to CMD.

RELEASING: documnent pushing packages to CMD

---

cloud_info_provider/providers/opennebula.py
cloud_info_provider/providers/openstack.py
cloud_info_provider/utils.py
etc/templates/compute.glue21

Update parsing of inbound/outbound network info of images.
Fix #149.

Fix network info

---

etc/templates/compute.cmdb.json

Add the missing compute template for CMDB

Add missing CMDB compute template

---

RELEASING.md

* Updates about the releasing process.

RELEASING: document making a release from CLI

---

cloud_info_provider/auth_refreshers/__init__.py
cloud_info_provider/auth_refreshers/oidc_refresh.py
cloud_info_provider/collectors/base.py
cloud_info_provider/collectors/cloud.py
cloud_info_provider/collectors/compute.py
cloud_info_provider/collectors/storage.py
cloud_info_provider/core.py
cloud_info_provider/exceptions.py
cloud_info_provider/formatters/base.py
cloud_info_provider/providers/__init__.py
cloud_info_provider/providers/ooi.py
cloud_info_provider/providers/opennebula.py
cloud_info_provider/providers/openstack.py
cloud_info_provider/providers/static.py
cloud_info_provider/tests/test_auth_refreshers.py
cloud_info_provider/tests/test_collectors.py
cloud_info_provider/tests/test_core.py
cloud_info_provider/tests/test_openstack.py
setup.cfg

Provides a way to extend authentication with pluggable python classes that will refresh the credentials as needed. 
----
**Related issue :** #160

External authentication plugins

---

cloud_info_provider/providers/ssl_utils.py
etc/templates/compute.glue21

Fix some of issues found while testing with Python3

Make it work with Python 3

---

cloud_info_provider/auth_refreshers/oidc_refresh.py
cloud_info_provider/auth_refreshers/oidc_vo_refresh.py
cloud_info_provider/providers/openstack.py
cloud_info_provider/tests/test_auth_refreshers.py
cloud_info_provider/tests/test_openstack.py
setup.cfg

New auth refresher to be used with the catchall-operations of fedcloud. Reads credentials for each VO from different files located under a configurable path

Refresh catchall

---

cloud_info_provider/core.py

Code was crashing as the wrong variable was used

Fix getting the refresher

---

cloud_info_provider/auth_refreshers/oidc_refresh.py
cloud_info_provider/tests/test_auth_refreshers.py

and of course fix the tests...
Fix issues found while testing for real in the fedcloud-catchall-ops

Fix authentication

---

.zenodo.json
debian/changelog
debs/cloud-info-provider-opennebula/debian/changelog
debs/cloud-info-provider-openstack/debian/changelog
rpm/cloud-info-provider-opennebula.spec
rpm/cloud-info-provider-openstack.spec
rpm/cloud-info-provider.spec

* Fix get instances for volume-based instances (Enol Fernández)
* Add external authentication plugin support (Enol Fernández)
* Add OpenID Connect refresh plugin (OpenStack) (Enol Fernández)   
* Python 3 fixes (Enol Fernández)
* Pythonize only for Ruby dict-like strings (Pablo Orviz)
* Fix: use is_public=None to fetch both public and private flavors. (Pablo Orviz)
* RELEASING: document making a release from CLI (Baptiste Grenier)
----
**Related issue :** #167

Prepare release 0.11.4

---

README.md
cloud_info_provider/providers/gocdb.py
cloud_info_provider/providers/opennebula.py
cloud_info_provider/providers/ssl_utils.py
cloud_info_provider/tests/test_gocdb.py

Fixes several issues found while testing with OpenNebula providers.
----
**Related issue :** #169

Several fixes for OpenNebula (and CentOS 7)

---

.zenodo.json
debian/changelog
debs/cloud-info-provider-opennebula/debian/changelog
debs/cloud-info-provider-openstack/debian/changelog
rpm/cloud-info-provider-opennebula.spec
rpm/cloud-info-provider-openstack.spec
rpm/cloud-info-provider.spec

Release 0.11.5
----
**Related issue : #117**

Preparation of release 0.11.5

---

.zenodo.json
README.md
debian/changelog
debs/cloud-info-provider-opennebula/debian/changelog
debs/cloud-info-provider-openstack/debian/changelog
rpm/cloud-info-provider-opennebula.spec
rpm/cloud-info-provider-openstack.spec
rpm/cloud-info-provider.spec

* Refactor SSL checks (#175). (Enol Fernández)
* Do not fail if JSON cannot be decoded (#176). (Enol Fernández)
* Code Clean-up (#177). (Enol Fernández)
* Import stdout (default one) and ams publishers (#178). (Enol Fernández)
----
**Related issue :** #179

Prepare release 0.12.0

---

Jenkinsfile

----
Removes unnecessary packages already existing in the build environment & updates the OpenStack release for CentOS7
**Related issue :** #182

Update list of requirements for CentOS7 RPM building

---

.travis.yml
tox.ini

upgrade testing python to python3.5 to avoid issues with PyYaml

Upgrade to python 3.5

---

CHANGELOG

Prepares the upcoming 0.12.1 release
---
**Related issue :** #199

Prepare release 0.12.1

---

.github/workflows/pre-release.yml
.github/workflows/release.yml
RELEASING.md

Updates the release workflow to create one PR that triggers
the creation of a release when merged

Update release workflow

---

.github/workflows/pre-release.yml

Use a specific GitHub App for triggering PRs

Add github app

---

.github/workflows/pre-release.yml

Use the token generated previously
---

Use the token generated by the app

---

cloud_info_provider/formatters/base.py
cloud_info_provider/formatters/templates/compute.glue21
cloud_info_provider/providers/openstack.py
test-requirements.txt

Fix some issues found while deploying the catchallops:
﻿- Do not silently ignore errors in rendering
- Do not fail if no templates are found

catchallops issues

---

cloud_info_provider/formatters/templates/compute.glue21
cloud_info_provider/formatters/templates/compute.ldif

Avoid failing when some data is not there
---

Avoid failing if endpoint is not available

---

cloud_info_provider/collectors/compute.py
cloud_info_provider/core.py
cloud_info_provider/tests/test_collectors.py
cloud_info_provider/tests/test_static.py

Fixes some issues found during testing the ignore-share option with the catch-all instance
---

Do really ignore share if not working

---

CHANGELOG

Release 0.12.2
---
**Related issue :** #223

Release 0.12.2

---

.github/workflows/pre-release.yml
.zenodo.json
README.md
RELEASING.md
debs/cloud-info-provider-opennebula/debian/control
debs/cloud-info-provider-openstack/debian/control
rpm/cloud-info-provider-opennebula.spec
rpm/cloud-info-provider-openstack.spec
rpm/cloud-info-provider.spec

Remove references to EGI-Foundation

Move to EGI-Federation

---

.zenodo.json

Moving the Zenodo org name from EGI-Foundation to egi
---

Rename Zenodo org

---

cloud_info_provider/providers/openstack.py
cloud_info_provider/tests/data.py
cloud_info_provider/tests/test_openstack.py

Endpoints for different regions change so publishing the right
info requires knowing which region we are using
This is coming as CNAF has different regions
---

Add region in the openstack provider

---

cloud_info_provider/auth_refreshers/oidc_vo_refresh.py

Avoid having a / at the VO name to find the path for the refresh token info. This is relevant when using a FQAN like name of VO
---

Remove '/' from beggining/end of VO name

---

.github/CONTRIBUTING.md
.github/workflows/packages.yml
.github/workflows/pre-release.yml
.github/workflows/python.yml
.github/workflows/release.yml
.github/workflows/superlinter.yml
.testr.conf
CHANGELOG
README.md
RELEASING.md
cloud_info_provider/formatters/templates/compute.glue21
cloud_info_provider/providers/openstack.py
cloud_info_provider/tests/data.py
cloud_info_provider/tests/test_openstack.py
etc/sample.opennebula.yaml
etc/sample.opennebularocci.yaml
etc/sample.openstack.yaml
etc/sample.static.yaml
test-requirements.txt
tox.ini

Templates do have human readable names that are not included in the current glue2 output. This should add them
---

Add template names

---

.github/workflows/packages.yml
.github/workflows/pre-release.yml
.github/workflows/python.yml
.github/workflows/release.yml
CHANGELOG
cloud_info_provider/providers/gocdb.py
cloud_info_provider/tests/test_gocdb.py
test-requirements.txt
tox.ini

Sites may choose to add URLs to the endpoints in GOCDB. Adding support for this case.
---

Add support for endpoints in GOCDB

---

.github/CONTRIBUTING.md
.github/workflows/superlinter.yml
Jenkinsfile
RELEASING.md

---
**Consider author for inclusion**:

Move to main

---

CHANGELOG

Prepare the new release 0.13.0
---
**Related issue :** #238

Release 0.13.0

---

pyproject.toml
setup.cfg

Just try to modernize the build of the cloud-info-provider
---

pbr upgrade

---

.github/workflows/pre-release.yml
.github/workflows/release.yml
.github/workflows/superlinter.yml
README.md

Look at addressing lint errors reported by super-linter.

Style with prettier

---

README.md

Fix badge syntax, adding a link to the workflow run

Fix badge syntax, adding a link to the workflow run

---

.github/dependabot.yml

---
**Consider author for inclusion**:

Move from pip to dependabot

---

cloud_info_provider/providers/openstack.py
cloud_info_provider/providers/utils.py
cloud_info_provider/tests/test_openstack.py

Publish potentially relevant metadata so we can get this information at the cloud-info-api
---

Add existing metadata to the other_info

---

cloud_info_provider/glue.py

Increase validity and add time zone
