EGI-Federation/cloud-info-provider

- cloud_info/providers/openstack.py
- cloud_info/providers/static.py
- cloud_info/tests/data.py
- cloud_info/tests/test_openstack.py
- etc/sample.static.yaml
- etc/templates/compute.ldif
I'm not sure if this is the right approach. Please, comment.
When updating ONe provider, I noticed that `compute.ldif` expects a field set only by the OpenStack provider and it fails for every other provider. This field was not namespaced (== prefixed) or treated as an endpoint field by the static provider.
The proposed change will require a version bump (slight changes in configuration files) but should work consistently across all providers. It mandates `endpoint_url` as an explicit field for `compute` endpoints.
> Fixed `endpoint_url` field in `compute`

- README.md
- debian/control
Document RPM and deb package building using containers.
python-support packages was removed from the repositories and in fact dh-python build dependency is sufficient.
> Document package building and fix build on Xenial

- .travis.yml
If `sudo` is not required, using containerized environment will give us faster builds.
> [CI] Support for containerized Travis-CI

- README.md
As python-pbr comes from a repository installed by centos-release-openstack-liberty it has to be installed in a second yum call.
> README: python-pbr comes from a repo configured by centos-release-openstack-liberty

- cloud_info/providers/openstack.py
This small patch adds the vmcatcher way of storing the image version in case the image_version metadata entry is not set.
> Optionally use the version entry from vmcatcher as image_version.

- cloud_info/providers/opennebula.py
Ref. https://ggus.eu/index.php?mode=ticket_info&ticket_id=129289
Using `[]` on a dictionary for a non-existent key will raise
an error. Using `.get()` is more appropriate here.
> Fixed deep hash lookup for ONe provider

- etc/templates/compute.ldif
Missing attribute was causing the following errors and breaking entry updates (at least on CentOS 7):
```
2017-11-09 15:22:18,808: [WARNING] ldap_modify: Naming violation (64)
2017-11-09 15:22:18,808: [WARNING] additional info: naming attribute 'GLUE2ApplicationEnvironmentID' is not present in entry
```
> Fixing entry updates for ApplicationEnvironment

- README.md
- debian/changelog
- debian/control
- rpm/cloud-info-provider.spec
- Use keystoneauth and v3 API, deprecate v2.0 API (Alvaro Lopez)
- OpenStack Identity API v2.0 has been deprecated and is *no more supported*
- Fix Fix entry updates for ApplicationEnvironment (Boris Parak)
- Update package building and documentation (Baptiste Grenier)
> Prepare version 0.9.0

- cloud_info/providers/openstack.py
Useful if the site does not support OCCI
> Avoid failing if one endpoint is not present

- debian/changelog
- rpm/cloud-info-provider.spec
Release 0.9.1
- OCCI is optional, do not fail if no OCCI endpoint is present (Enol Fernandez)
- Update organization name in documentation (Baptiste Grenier)
> Prepare release 0.9.1

- README.md
Package building example is using xenial not trusty.
> README: fix typo on ubuntu codename.

- cloud_info/tests/test_openstack.py
- cloud_info/tests/utils.py
In order to validate that fields used within the templates are correctly
populated by the OpenStack provider, they are extracted from the
templates.
With the switch to Mako the regex used to match them was obsoleted, this PR
fixes the regex and fixes the tests.
> Fix retrieval of fields from the template for tests.

- README.md
- cloud_info/providers/openstack.py
- cloud_info/tests/test_openstack.py
As documented on https://docs.openstack.org/nova/pike/admin/flavors.html :
a public flavor is a flavor that is not restricted to the current project.
Previously only public flavors were returned, it is now possible to select all
(default), public or private only flavors. Fix #82.
> OpenStack provider: add a provider-specific argument to manage templates/flavors selection.

- debian/control
- debian/copyright
- rpm/cloud-info-provider.spec
As the repository was moved under the EGI-Foundation organisation it's appropriate to update references still present here and there.
> Update references to EGI-FCTF to point to EGI-Foundation

- Jenkinsfile
- tox.ini
Cobertura report was generated in Jenkinsfile using a temporary tox.ini.cobertura file. In order to keep Jenkins configuration cleaner, the report is created using a new Tox environment, called 'cobertura'. 
On the other hand, Jenkinsfile executes the 'cover' environment and was wrongly expecting a HTML report, thus marking the job as a failure. This latter part has been removed.
----
**Consider author for inclusion**:
> Generates Jenkins cobertura report using a Tox environment.

- README.md
- cloud_info_provider/core.py
- cloud_info_provider/providers/openstack.py
- cloud_info_provider/tests/data.py
- cloud_info_provider/tests/test_openstack.py
- cloud_info_provider/tests/test_static.py
This moves the OCCI-specific code of the OpenStack provider to a new ooi provider. This will allow to easily support antive OpenStack without OCCI and to adapt to publishing to AMS using independent topics for each service endpoint in GOCDB.
> Split ooi and OpenStack providers

- cloud_info_provider/providers/opennebula.py
- cloud_info_provider/providers/openstack.py
- cloud_info_provider/providers/static.py
- cloud_info_provider/tests/data.py
- cloud_info_provider/tests/test_openstack.py
- etc/sample.opennebula.yaml
- etc/sample.opennebularocci.yaml
- etc/sample.openstack.yaml
This change tries to make more clear the usage of project ID in the configuration. The layout has been slightly modified so the `project_id` attribute falls under the `auth` category. In addition, the variables used in the code now refer to `project_id` (instead of the former `project`).
Closes #118 
----
**Related issue : #117 **
> Make the usage of project ID more clear in code and configuration files

- cloud_info_provider/providers/ssl_utils.py
Use default port 443 for SSL checks when not specified in the URL of the cloud middleware
----
**Related issue :** #140
> Use 443 port as default for https

- cloud_info_provider/providers/openstack.py
According to https://developer.openstack.org/api-ref/compute/?expanded=list-flavors-detail#list-flavors
> Fix: use is_public=None to fetch both public and private flavors.

- cloud_info_provider/utils.py
[atrope](https://github.com/alvarolopez/atrope) already adds JSON compliant values for `ad:traffic_in` and `ad:traffic_out` appliance attributes for glance images, thus `pythonize_network_info` should not be applied in this case.
> Pythonize only for Ruby dict-like strings

- cloud_info_provider/providers/openstack.py
- cloud_info_provider/tests/test_openstack.py
Fix the case when the instance is started from a Volume as OpenStack returns an empty-string in this case, instead of a dict with the image details.
> Fix get instances for volume-based instances

- cloud_info_provider/core.py
- cloud_info_provider/providers/gocdb.py
- cloud_info_provider/providers/ooi.py
- cloud_info_provider/providers/openstack.py
- cloud_info_provider/providers/static.py
- cloud_info_provider/tests/base.py
- cloud_info_provider/tests/data.py
- cloud_info_provider/tests/test_auth_refreshers.py
- cloud_info_provider/tests/test_base_provider.py
- cloud_info_provider/tests/test_collectors.py
- cloud_info_provider/tests/test_core.py
- cloud_info_provider/tests/test_formatters.py
- cloud_info_provider/tests/test_openstack.py
- cloud_info_provider/tests/test_static.py
- cloud_info_provider/utils.py
- etc/sample.static.yaml
Improve testing, removing not used code
----
**Related issue :** N/A
> Code clean-up

- README.md
- cloud_info_provider/core.py
- cloud_info_provider/formatters/base.py
- cloud_info_provider/providers/base.py
- cloud_info_provider/providers/gocdb.py
- cloud_info_provider/providers/opennebula.py
- cloud_info_provider/providers/openstack.py
- cloud_info_provider/publishers/ams.py
- cloud_info_provider/publishers/base.py
- cloud_info_provider/publishers/stdout.py
- cloud_info_provider/tests/test_base_provider.py
- cloud_info_provider/tests/test_core.py
- cloud_info_provider/tests/test_gocdb.py
- cloud_info_provider/tests/test_openstack.py
- cloud_info_provider/tests/test_publishers.py
- setup.cfg
This PR brings pluggable support for the output. 2 initial publishers are provided: `stdout` (the one we already had) and `ams` for pushing messages to ARGO AMS
> Publishers: stdout and AMS

- cloud_info_provider/providers/gocdb.py
- cloud_info_provider/providers/opennebula.py
- test-requirements.txt
This is deprecated in py2.7 and not available in py3
> Avoid use of getchildren

- cloud_info_provider/collectors/compute.py
- cloud_info_provider/providers/base.py
- cloud_info_provider/providers/openstack.py
- cloud_info_provider/tests/test_collectors.py
- cloud_info_provider/tests/test_openstack.py
- etc/templates/compute.glue21
- setup.cfg
Adds the project name and project domain name for easing discovery
----
**Related issue :** #186
> Add project name and project domain name

- .github/linters/.jscpd.json
- cloud_info_provider/collectors/compute.py
- cloud_info_provider/core.py
- cloud_info_provider/tests/test_collectors.py
Add option to ignore errors when getting information for share, so cloud-info-provider can still produce results for other shares configured in the resources. This avoids crashes although can hide errors
---
> New ignore errors option

- cloud_info_provider/auth_refreshers/oidc_refresh.py
- cloud_info_provider/core.py
- cloud_info_provider/providers/base.py
- cloud_info_provider/providers/gocdb.py
- cloud_info_provider/providers/openstack.py
- cloud_info_provider/publishers/ams.py
- cloud_info_provider/tests/test_auth_refreshers.py
- cloud_info_provider/tests/test_base_provider.py
- cloud_info_provider/tests/test_gocdb.py
- cloud_info_provider/tests/test_publishers.py
Add timeout as a general option so it can be used everywhere.
Also add timeout to all the requests calls in the code.
---
**Related issue :** #216
> Add timeout option to core

- cloud_info_provider/auth_refreshers/oidc_refresh.py
- cloud_info_provider/auth_refreshers/oidc_vo_refresh.py
- cloud_info_provider/providers/opennebula.py
Allow the refresh of tokens without the client_secret for the new fedcloud client
---
> Refresh without client secret

- cloud_info_provider/formatters/templates/compute.glue21
- cloud_info_provider/providers/openstack.py
- cloud_info_provider/tests/test_formatters.py
Improves the GPU information gathering for OpenStack and publishing via GLUE2.1.
Uses the agreed flavor properties `Accelerator:XXX` as defaults
Adds a simple test to check that the templates do not have syntax errors
---
**Related issue :** #239
> Add GPU information to templates

- cloud_info_provider/auth_refreshers/__init__.py
- cloud_info_provider/auth_refreshers/access_token.py
- cloud_info_provider/auth_refreshers/oidc_refresh.py
- cloud_info_provider/providers/openstack.py
- cloud_info_provider/tests/test_auth_refreshers.py
- cloud_info_provider/tests/test_openstack.py
- setup.cfg
This change brings support to use access tokens directly for authentication to the OpenStack projects. For every share, the `accesstoken` refresher will take the information available in the `auth` config of the share and just pass it to the OpenStack provider so it can be further used. It does not try to refresh or any other kind of magic, the token is assumed to be valid for the project.
Sample configuration:
```
compute:
shares:
vo-name:
auth:
project_id: "the project id"
access_token: "<the access token>"
```
Using it from command line:
```
$ cloud-info-provider-service \
--yaml-file openstack.yaml \
--middleware openstack \
--auth-refresher accesstoken \
--os-auth-type v3oidcaccesstoken \
--os-identitiy-provider egi.eu \
--os-protocol openid \
--format glue21
```
---
**Related issue …
> Get ready for refreshing just with access tokens

- cloud_info_provider/providers/utils.py
Potential fix for [https://github.com/EGI-Federation/cloud-info-provider/security/code-scanning/2](https://github.com/EGI-Federation/cloud-info-provider/security/code-scanning/2)
To fix the issue, we will replace the use of `SSL.SSLv23_METHOD` with `SSL.TLSv1_2_METHOD`. This explicitly enforces the use of TLSv1.2, a secure and modern protocol. Additionally, we will retain the existing options (`SSL.OP_NO_SSLv2` and `SSL.OP_NO_SSLv3`) for completeness, although they are redundant when using `TLSv1_2_METHOD`.
The changes will be made in the `get_endpoint_ca_information` function in the file `cloud_info_provider/providers/utils.py`. Specifically, we will update the line where the SSL context is created.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 2: Use of insecure SSL/TLS version
